apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: springboot
  template:
    metadata:
      name: springbootpod
      labels:
        name: springboot
         spec:
      containers:
      - image: dockerhandson/spring-boot-mongo:latest
        name: springbootcontainer
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_USERNAME
          value: devdb
        - name: MONGO_DB_PASSWORD
          value: devdb@123
        - name: MONGO_DB_HOSTNAME
          value: mongo
          ---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  name: spring-svc
  labels:
    name: springboot
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: springboot
    ---
# Mongo host path rc
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-rc
  labels:
    name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: devdb
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: devdb@123 
       ---
# Mongo Node Port RC
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  labels:
    name: mongo
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
